### ISSUE TITLE
Add CI check on `master` that mangrove.js ABI's match ABI's of deployed contracts

### ISSUE THREAD

**Issue by espendk** [mangrovedao/mangrove#259]
**Is your feature request related to a problem? Please describe.**
The root cause of issue #256 was that the ABI for Mangrove had changed on `master` (including in mangrove.js), but the new version of the contract hadn't been deployed. This meant that mangrove.js couldn't understand the events of the Mangrove contract instance it was connecting to.

**Describe the solution you'd like**
There should be a CI check on `master` which verifies that the ABI's in mangrove.js match those on the relevant block explorers or (for Mangrove contracts) those in the `deployments` folder of `mangrove-solidity`:

- The ABI's contained in mangrove.js will be part of the checked out code in CI, e.g. https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove.js/src/abis/Mangrove.json
- The ABI's for Mangrove contract deployments will also be part of the checked out code in CI, e.g. https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove-solidity/deployments/mumbai/Mangrove.json
- The ABI for the verified contract can be fetched from PolygonScan using their API: [docs.polygonscan.com/api-endpoints/contracts#get-contract-abi-for-verified-contract-source-codes](https://docs.polygonscan.com/api-endpoints/contracts#get-contract-abi-for-verified-contract-source-codes). Similar API's should exist for other block explorers.

Comparing the ABI's can probably be done using something like `fast-equals` or `lodash`.

**Describe alternatives you've considered**
A warning when ABI files change stating that one must remember to redeploy Mangrove.

**Additional context**
None

**Comment by adhusson** [comment]
Taking another look at this, here are my current thoughts -- would love to have a thorough discussion on this:

#256 was due to mangrove.js talking to a Mangrove instance that was not ABI-compatible with mangrove.js' internal code.

If you consider the larger issue "mangrove contracts not matched with mangrove.js", there are 2 ways to trigger this:
  1. **Onchain contract too old**: either
    a. Generally: update mangrove-solidity & mangrove.js in sync, but don't redeploy mangrove contracts. 
    b. Specifically for the ABI case: Update mangrove-solidity's ABIs (the ABIs should be auto-propagated to mangrove.js by building), but don't redeploy mangrove contracts.
  2. **Onchain contract too new**: Redeploy mangrove contracts with semantics that are incompatible with mangrove.js (the new address should be auto-propagated to mangrove.js by a PR), but don't update mangrove.js.

Checking the onchain ABI fixes 1.b. only, and requires complex & subtle fiddling with ABIs since the expressivities available at the etherscan level and locally are not the same. This fiddling can easily be broken by updates to the mangrove contracts.

The different tradeoffs lead me to this for now:

* For issue 1., the analogy in my head is "trying to talk to the prod server with the dev client". We can fix the problem by either (a) testing that the dev client can talk to the prod server (not just to the dev server), or (b) testing dev client <-> prod server whenever the dev client changes its declared prod server version. So in our case, either (a) running integration tests on forks (would immediately reveal that there's an issue, which is great, but it means being forced to live on a long-lived feature branch for developments that take a while and update both mangrove contracts & mangrove.js, which is an acceptable tradeoff to me), or (b) run tests on forks _only_ after the mangrove address has changed in mangrove.js.
* For issue 2. on a testnet/mainnet, since new onchain mangrove contracts deployments are already "heavy" (there's a whole checklist to go through), add a manual step "update mangrove addresses on mangrove.js when mangrove.js is ready" (@dontrolle I believe we added an auto-PR for that, but if the steps are followed where could the issue arise?). This should take care of 2. for testnet/mainnet.
* For 2. on local nodes, later, when mangrove.js/mangrove-solidity don't live in the same repo, mangrove.js will be able to pin a mangrove-solidity version/commit, and issue 2. will also go away for local testing (for now any update to mangrove-solidity means that local nodes will use the newest version and thus require mangrove.js to be compatible with the new contracts).

**Comment by dontrolle** [comment]
Waiting with this until we have a stable state for now.

**Comment by adhusson** [comment]
Update on this: since we separated the repos, mangrove.js is pinned to a specific mangrove-core version.

As a reminder, the 2 possible issues are:

1. Solidity code/ABI is updated, mangrove.js picks up the changes, but the new contracts are not deployed. This is what caused #256 and what Peter did an impressive fix for through etherscan & manual ABI-rewriting in #630.
2. The other way around: new contracts are deployed, mangrove.js uses the new address, but the ABI/semantics changed and mangrove.js does not know that.

With the repo separation, contracts are decoupled from mangrove.js. So to trigger 1. the following needs to happen:
* Someone makes an ABI change to mangrove-core
* And publishes a new mangrove-core version without deploying the new contracts
* Mangrove.js updates its dependency to the new mangrove-core version
* Mangrove.js gets published in that broken state

I don't think this scenario is likely enough to warrant worrying about it.

Triggering 2. is even harder since you would have to circumvent mangrove-core's normal upgrade procedure to change the addresses without changing the ABI.

So I'm for closing the issue, wdyt?

**Comment by jkrivine** [comment]
Sounds good yes.

**Comment by lnist** [comment]
I remember @peterMangrove had an almost working version - however, I also agree that the likelihood is low, and since we pin mangrove.js to a version which is published I would vote for the check to be around the publishing instead if we had it - not being able to publish a version with a wrong abi. For now, the checklist makes sure of that (at least it does, when it is created)

**Comment by dontrolle** [comment]
I'm fine with closing this, for now - for the reasons you've already listed above. Let's archive https://github.com/mangrovedao/mangrove/pull/630 as well.
